version: "2"

plugins:
  eslint:
    enabled: true
    channel: "eslint-4"
    config:
      config: .eslintrc
      extensions:
        - .jsx
        - .js

exclude_patterns:
  - "config/*"
  - "scripts/*"
  - "package.json"

checks:
  argument-count:
    enabled: false
  file-lines:
    enabled: false
  method-count:
    enabled: false
  method-lines:
    enabled: false
  similar-code:
    enabled: false
  identical-code:
    enabled: false
