version: "2"

checks:
  method-lines:
    enabled: false
  similar-code:
    enabled: false
  identical-code:
    enabled: false

plugins:
  eslint:
    enabled: true
    channel: "eslint-4"
    config:
      file: .eslintrc
      extensions:
        - .es6
        - .js

exclude_patterns:
  - "*.config.*"
  - "tools/*"
  - "package.json"
