engines:
  eslint:
    enabled: true
    channel: "eslint-4"
    config:
        config: .eslintrc
        extensions:
        - .es6
        - .js
ratings:
   paths:
   - "src/**/*.js"
checks:
  method-lines:
    enabled: false

plugins:
  ESLint:
    enabled: true

exclude_patterns:
  - "*.config.*"
  - "tools/*"
  - "package.json"
