version: "2"

plugins:
  eslint:
    enabled: true
    channel: "eslint-4"
    config:
      file: .eslintrc
      extensions:
        - .js

exclude_patterns:
  - "config/*"
  - "scripts/*"
  - "package.json"
