version: "2"

plugins:
  eslint:
    enabled: true
    channel: "eslint-4"
    checks:
      method-lines:
        enabled: false
    config:
      file: .eslintrc
      extensions:
        - .es6
        - .js

exclude_patterns:
  - "*.config.*"
  - "tools/*"
  - "package.json"
