version: 2.0

workflows:
  version: 2
  test_build_deploy:
    jobs:
      - build
      - deploy-dev:
          requires:
            - build
          filters:
            branches:
              only: dev
      - deploy-pre:
          requires:
            - build
          filters:
            branches:
              only: master
      - hold:
         type: approval
         requires:
           - deploy-pre
      - deploy-prod:
          requires:
            - hold
          filters:
            branches:
              only: master

jobs:
  build:
    environment:
      CC_TEST_REPORTER_ID: c8948572d88557d3a8f8b1e4ce7e84dc2dc8b36f31fd6deb6707ba0c6e1cb02a
    docker:
      - image: circleci/node:6
    steps:
      - checkout
      - restore_cache:
          key: dependency-cache-{{ checksum "package.json" }}
      - run:
          name: Setup dependencies
          command: yarn install
      - run:
          name: Setup Code Climate test-reporter
          command: |
            curl -L https://codeclimate.com/downloads/test-reporter/test-reporter-latest-linux-amd64 > ./cc-test-reporter
            chmod +x ./cc-test-reporter
      - save_cache:
          key: dependency-cache-{{ checksum "package.json" }}
          paths:
            - node_modules
      - run:
          name: Run tests
          command: |
            yarn test
            ./cc-test-reporter after-build < coverage/lcov.info
      - run:
          name: Build
          command: yarn build

  deploy-dev:
    docker:
      - image: circleci/node:6
    steps:
      - checkout
      - run:
          name: Install awscli
          command: sudo apt-get update && sudo apt-get install awscli
      - run:
          name: Setup dependencies
          command: yarn install
      - run:
          name: Install dependencies
          command: yarn install
      - run:
          name: Build
          command: yarn build
      - run:
          name: DEPLOY DEV
          command: aws s3 sync build/ s3://snt-dev --region us-east-1

  deploy-pre:
    docker:
      - image: circleci/node:6
    steps:
      - checkout
      - run:
          name: Install awscli
          command: sudo apt-get update && sudo apt-get install awscli
      - run:
          name: Setup dependencies
          command: yarn install
      - run:
          name: Install dependencies
          command: yarn install
      - run:
          name: Build
          command: yarn build
      - run:
          name: DEPLOY PRE
          command: aws s3 sync build/ s3://snt-pre --region us-east-1

  deploy-prod:
    docker:
      - image: circleci/node:6
    steps:
      - checkout
      - run:
          name: Install awscli
          command: sudo apt-get update && sudo apt-get install awscli
      - run:
          name: Setup dependencies
          command: yarn install
      - run:
          name: Install dependencies
          command: yarn install
      - run:
          name: Build
          command: yarn build
      - run:
          name: DEPLOY PROD
          command: aws s3 sync build/ s3://snt-prod --region us-east-1
