version: 2.0

workflows:
  version: 2
  build_and_test:
    jobs:
      - build
      - test:
          requires:
            - build
          filters:
            branches:
              only: master

jobs:
  build:
    docker:
      - image: circleci/node:7-browsers
    steps:
      - checkout
      - restore_cache:
        key: dependency-cache-{{ checksum "package.json" }}
      - run:
        name: npm Install
        command: npm install
      - save_cache:
        key: dependency-cache-{{ checksum "package.json" }}
        paths:
          - node_modules

  test:
    docker:
      - image: circleci/node:7-browsers
    steps:
      - checkout
      - run:
        name: Test
        command: npm run test
      - run:
        name: Generate code coverage
        command: npm run test:CI
      - store_artifacts:
        path: coverage
        prefix: coverage

#machine:
#  node:
#    version:
#      8.2.1
#
#  environment:
#    NODE_ENV: development
#    CIRCLE_ARTIFACTS: "coverage"
#
#dependencies:
#  override:
#    - npm install:
#        timeout: 180
#
#test:
#  override:
#    - yarn run test:CI
#  post:
#      - yarn run cover
#
#deployment:
#  production:
#    branch: master
#    commands:
#      - yarn run publish:pro
#  staging:
#    branch: pre
#    commands:
#      - yarn run publish:pre
#  dev:
#    branch: dev
#    commands:
#      - yarn run publish:dev
#
