version: 2.0

workflows:
  version: 2
  test_build_deploy:
    jobs:
      - test
      - build:
          requires:
            - test
      - coverage:
          requires:
            - test
      - deploy-dev:
          requires:
            - build
            - coverage
          filters:
            branches:
              only: dev
      - deploy-pre:
          requires:
            - build
            - coverage
          filters:
            branches:
              only: master
      - deploy-prod:
          requires:
            - deploy-pre
          filters:
            branches:
              only: master


jobs:
  test:
       docker:
         - image: circleci/node:6
    steps:
      - run:
          name: yarn test
          command: yarn test
  build:
    steps:
      - run:
          name: Build
          command: yarn build
  coverage:
    steps:
      - run:
          name: yarn test
          command: "echo Coverage"
  deploy-dev:
    steps:
      - run:
          name: yarn test
          command: "echo DEPLOY DEV"
  deploy-pre:
    steps:
      - run:
          name: yarn test
          command: "echo DEPLOY PRE"
  deploy-prod:
    steps:
      - run:
          name: yarn test
          command: "echo DEPLOY PROD"

#   build:
#     docker:
#       - image: circleci/node:6
#     environment:
#       - NODE_ENV: development
#     steps:
#       - checkout
#       - restore_cache:
#           key: dependency-cache-{{ checksum "package.json" }}
#       - run:
#           name: yarn Install
#           command: yarn install
#
#       - save_cache:
#           key: dependency-cache-{{ checksum "package.json" }}
#           paths:
#             - node_modules
#
#   test:
#     docker:
#       - image: circleci/node:7-browsers
#     steps:
#       - checkout
#       - run:
#           name: Test
#           command: yarn test
#       - store_artifacts:
#           path: coverage
#           prefix: coverage
#
#machine:
#  node:
#    version:
#      8.2.1
#
#  environment:
#    NODE_ENV: development
#    CIRCLE_ARTIFACTS: "coverage"
#
#dependencies:
#  override:
#    - npm install:
#        timeout: 180
#
#test:
#  override:
#    - yarn run test:CI
#  post:
#      - yarn run cover
#
#deployment:
#  production:
#    branch: master
#    commands:
#      - yarn run publish:pro
#  staging:
#    branch: pre
#    commands:
#      - yarn run publish:pre
#  dev:
#    branch: dev
#    commands:
#      - yarn run publish:dev
#
